import type { Message, ContentBlock } from '../engine/types.js'
import type { NexusConfig } from '../config.js'
import type { ModelClient } from '../routing/types.js'
import type { ContextAction, DecayTier } from './types.js'
import { estimateTokens } from '../utils/tokens.js'

type ContextManagerDeps = {
  config: NexusConfig
  /** Local model client for generating summaries (free) */
  localClient?: ModelClient
}

// Tool result blocks that are safe to decay (same concept as Claude Code's COMPACTABLE_TOOLS)
const COMPACTABLE_TOOLS = new Set(['Bash', 'ReadFile', 'Grep', 'WriteFile'])

/**
 * Tiered tool result decay engine.
 * Pattern from Claude Code's microCompact.ts + toolResultStorage.ts.
 *
 * Turn 0-N:         full result
 * Turn N+1 to M:    summary (generated by local model — free)
 * Turn M+1+:        one-line stub
 */
export function createContextManager(deps: ContextManagerDeps) {
  const { config } = deps
  const summaryCache = new Map<string, string>() // tool_use_id -> summary

  /** Generate a summary of a tool result using the local model. */
  async function summarizeToolResult(toolName: string, content: string, signal?: AbortSignal): Promise<string> {
    if (!deps.localClient || !(await deps.localClient.isAvailable())) {
      // Fallback: take first 200 chars
      return content.slice(0, 200) + (content.length > 200 ? '...' : '')
    }

    const prompt = `Summarize this ${toolName} tool result in one concise paragraph. Focus on key findings, outcomes, and any errors. Be factual and brief:\n\n${content.slice(0, 5000)}`

    let summary = ''
    const stream = deps.localClient.stream({
      model: config.exoModel,
      systemPrompt: 'You are a concise summarizer. Output only the summary, nothing else.',
      messages: [{ role: 'user', content: [{ type: 'text', text: prompt }], turn: 0 }],
      tools: [],
      maxTokens: 200,
      signal,
    })

    for await (const event of stream) {
      if (signal?.aborted) break
      if (event.type === 'text_delta') summary += event.text
    }

    return summary.trim() || content.slice(0, 200)
  }

  /** Determine the decay tier for a message based on its age. */
  function getDecayTier(turnCreated: number, currentTurn: number): DecayTier {
    const age = currentTurn - turnCreated
    if (age <= config.contextDecayFullTurns) return 'full'
    if (age <= config.contextDecaySummaryTurns) return 'summary'
    return 'stub'
  }

  return {
    /**
     * Apply tiered decay to messages before an API call.
     * Returns a new message array with old tool results decayed.
     */
    async applyDecay(messages: Message[], currentTurn: number, signal?: AbortSignal): Promise<{
      messages: Message[]
      actions: ContextAction[]
    }> {
      const result: Message[] = []
      const actions: ContextAction[] = []

      for (let i = 0; i < messages.length; i++) {
        const msg = messages[i]!
        if (msg.role !== 'user') {
          result.push(msg)
          continue
        }

        // Check if this message contains tool results
        const hasToolResults = msg.content.some(b => b.type === 'tool_result')
        if (!hasToolResults) {
          result.push(msg)
          continue
        }

        const tier = getDecayTier(msg.turn, currentTurn)
        if (tier === 'full') {
          result.push(msg)
          continue
        }

        // Decay tool result blocks
        const newContent: ContentBlock[] = []
        let totalSaved = 0

        for (const block of msg.content) {
          if (block.type !== 'tool_result') {
            newContent.push(block)
            continue
          }

          const originalTokens = estimateTokens(block.content)

          if (tier === 'stub') {
            // Collapse to one-line stub
            const firstLine = block.content.split('\n')[0]?.slice(0, 80) ?? ''
            const stub = `[Tool result cleared — ${firstLine}]`
            newContent.push({ ...block, content: stub })
            totalSaved += originalTokens - estimateTokens(stub)
          } else {
            // Summary tier — use local model or cache
            let summary = summaryCache.get(block.tool_use_id)
            if (!summary) {
              // Find the tool name from the preceding assistant message
              const prevMsg = i > 0 ? messages[i - 1] : undefined
              const toolUse = prevMsg?.content.find(
                b => b.type === 'tool_use' && b.id === block.tool_use_id
              )
              const toolName = toolUse && 'name' in toolUse ? toolUse.name : 'unknown'
              summary = await summarizeToolResult(toolName, block.content, signal)
              summaryCache.set(block.tool_use_id, summary)
            }
            newContent.push({ ...block, content: `[Summary] ${summary}` })
            totalSaved += originalTokens - estimateTokens(summary)
          }
        }

        if (totalSaved > 0) {
          actions.push({
            type: tier === 'stub' ? 'decay_to_stub' : 'decay_to_summary',
            messageIndex: i,
            tokensSaved: totalSaved,
            tier,
          })
        }

        result.push({ ...msg, content: newContent })
      }

      return { messages: result, actions }
    },

    /** Get decay stats for the current message history. */
    getStats(messages: Message[], currentTurn: number) {
      let fullCount = 0, summaryCount = 0, stubCount = 0
      let originalTokens = 0, currentTokens = 0

      for (const msg of messages) {
        if (msg.role !== 'user') continue
        for (const block of msg.content) {
          if (block.type !== 'tool_result') continue
          const tier = getDecayTier(msg.turn, currentTurn)
          const tokens = estimateTokens(block.content)
          originalTokens += tokens
          currentTokens += tokens
          if (tier === 'full') fullCount++
          else if (tier === 'summary') summaryCount++
          else stubCount++
        }
      }

      return { fullCount, summaryCount, stubCount, originalTokens, currentTokens }
    },
  }
}

export type ContextManager = ReturnType<typeof createContextManager>
